import * as fs from 'node:fs'
import path from 'node:path'
import { breakpointsToScssMapValue } from './generateBreakpoints.ts'
import {
  colorTokensMapToScssMapValue,
  customColorTokensToScssMapValue,
  semanticColorAliasDefsToScssMapValue,
} from './generateColorTokens.ts'
import { fluidScaleToScssMapValue } from './generateFluidScale.ts'
import { fontFacesToScssListValue, metricsToScssMapValue } from './generateFontMetrics.scss.ts'
import { computeFontData } from './generateFonts.ts'
import { buildUtilityClassesMarkdown } from './generateUtilityClassesDoc.ts'
import {
  dynamicLineHeightToScssMapValue,
  fontRolesToScssMapValue,
  fontWeightsToScssMapValue,
  lineHeightsToScssMapValue,
  modularTypographicScaleToScssMapValue,
  semanticFontSizesToScssMapValue,
} from './generateTypography.ts'
import { setScssMapEntries, setScssMapValue, setWithArg } from './helpers.ts'
import { loadConfig, resolveOutDir } from './loadConfig.ts'

const cfg = await loadConfig()
const outDir = resolveOutDir(cfg)
const spacing = cfg.spacingSetup
const baseGridSize = spacing.baseGridSize ?? 4

const { metrics, fontFaces } = await computeFontData(cfg)

// Spacing: two mutually-exclusive shapes (coupled/independent), see
// models/Config.ts's SpacingSetup and abstracts/variables/_spacing.scss.
const spacingArgs =
  spacing.approach === 'coupled'
    ? [
        setWithArg('spacing-approach', '"coupled"'),
        setWithArg('t-shirt-scale', setScssMapValue(setScssMapEntries(spacing.tShirtScale, 2))),
        setWithArg('numeric-scale-end', `${spacing.numericScaleEnd}`),
      ]
    : [
        setWithArg('spacing-approach', '"independent"'),
        setWithArg('macro-range-max', `${baseGridSize * (spacing.macroRangeMultiplier ?? 2)}`),
        setWithArg('t-shirt-scale-micro', setScssMapValue(setScssMapEntries(spacing.tShirtScaleMicro, 2))),
        setWithArg('t-shirt-scale-macro', setScssMapValue(setScssMapEntries(spacing.tShirtScaleMacro, 2))),
        setWithArg('numeric-scale-micro-end', `${spacing.numericScaleMicroEnd}`),
        setWithArg('numeric-scale-macro-end', `${spacing.numericScaleMacroEnd}`),
      ]

const withArgs = [
  setWithArg('breakpoints', breakpointsToScssMapValue(cfg.breakpoints)),
  setWithArg('ultrawide-height-threshold-px', `${cfg.ultrawideHeightThresholdPx ?? 944}px`),
  setWithArg('fluid-scale', fluidScaleToScssMapValue(cfg.fluidScale)),
  setWithArg('font-metrics', metricsToScssMapValue(metrics)),
  setWithArg('font-faces', fontFacesToScssListValue(fontFaces)),
  setWithArg('font-roles', fontRolesToScssMapValue(cfg.fontRoles)),
  setWithArg('modular-typographic-scale', modularTypographicScaleToScssMapValue(cfg.modularTypographicScale)),
  setWithArg('semantic-font-sizes', semanticFontSizesToScssMapValue(cfg.semanticFontSizes)),
  setWithArg('font-weights', fontWeightsToScssMapValue(cfg.fontWeights)),
  setWithArg('line-heights', lineHeightsToScssMapValue(cfg.lineHeights)),
  setWithArg('dynamic-line-height', dynamicLineHeightToScssMapValue(cfg.dynamicLineHeight)),
  setWithArg('default-scheme', cfg.defaultScheme),
  setWithArg('base-color-tokens', colorTokensMapToScssMapValue(cfg.baseColorTokens)),
  setWithArg('custom-color-tokens', customColorTokensToScssMapValue(cfg.customColorTokens)),
  setWithArg('semantic-color-alias-defs', semanticColorAliasDefsToScssMapValue(cfg.semanticColorAliases)),
  setWithArg('base-grid-size', `${baseGridSize}`),
  ...spacingArgs,
].join('')

const output = `// AUTO-GENERATED by \`trimscale-css generate\` — do not edit by hand.
// Configures trimscale-css's static package internals (in node_modules,
// never regenerated) with this project's trimscale.config.ts, then pulls in
// this project's own generated @font-face rules alongside it.
// → docs/getting-started.md

// Leaf function file only (not the abstracts/functions index) — the index
// also forwards fn_fluid-typography-and-spacing, which @uses abstracts/variables,
// and loading that unconfigured here (before the with() below) would lock
// in its defaults before this file gets a chance to override them.
@use "abstracts/functions/fn_unit-utils" as fn;
@use "trimscale" with (
${withArgs});
`

fs.mkdirSync(outDir, { recursive: true })
fs.writeFileSync(path.join(outDir, '_index.scss'), output)
console.log(`- Bridge file is written to ${path.relative(process.cwd(), path.join(outDir, '_index.scss'))}`)

fs.writeFileSync(path.join(outDir, 'utility-classes.md'), buildUtilityClassesMarkdown(cfg))
console.log(
  `- Utility class reference is written to ${path.relative(process.cwd(), path.join(outDir, 'utility-classes.md'))}`,
)
