import type { TrimscaleConfig } from '../models/Config.ts'
import type { ResolvedUtilityFlags } from './generateUtilities.ts'
import { toKebabCase } from './helpers.ts'

const list = (keys: string[], prefix: string): string =>
  keys.length > 0 ? keys.map((key) => `\`.${prefix}${key}\``).join(', ') : '_none configured_'

const backticks = (values: string[]): string => values.map((value) => `\`${value}\``).join(', ')

/** T-shirt tier keys actually in use, from whichever `spacingSetup.approach` shape is active. */
const tShirtKeys = (spacing: TrimscaleConfig['spacingSetup']): string[] =>
  spacing.approach === 'coupled'
    ? Object.keys(spacing.tShirtScale)
    : [...new Set([...Object.keys(spacing.tShirtScaleMicro), ...Object.keys(spacing.tShirtScaleMacro)])]

/**
 * Builds a markdown reference of every utility class this project's
 * `trimscale.config.ts` actually produces. The config-driven sections
 * (typography roles/sizes/weights, spacing tiers) list this project's real
 * resolved names, not a generic example, they're read straight from `cfg`.
 * The fixed sections (never vary by config) are summarized with a pointer
 * to the full docs. `flags` mirrors the same `utilities`-derived booleans
 * `generateBridge.ts` passes into the SCSS bridge (see
 * `generateUtilities.ts`), so a group turned off there is left out here
 * too rather than documenting classes that don't exist. Written by
 * `generateBridge.ts` alongside the bridge file, into this project's own
 * `outDir`, never into node_modules.
 */
export const buildUtilityClassesMarkdown = (cfg: TrimscaleConfig, flags: ResolvedUtilityFlags): string => {
  const fontRoleKeys = Object.keys(cfg.fontRoles)
  // semanticFontSizes' keys are kebab-cased by generateTypography.ts before
  // becoming SCSS map keys (textLg -> text-lg); fontRoles/fontWeights/
  // lineHeights keys are used verbatim there, so they aren't converted here.
  const fontSizeKeys = Object.keys(cfg.semanticFontSizes).map(toKebabCase)
  const lineHeightKeys = Object.keys(cfg.lineHeights)
  const fontWeightKeys = Object.keys(cfg.fontWeights)
  const spacingKeys = tShirtKeys(cfg.spacingSetup)
  const spacingProperties = ['m', 'mx', 'my', 'mt', 'mb', 'ml', 'mr', 'p', 'px', 'py', 'pt', 'pb', 'pl', 'pr']
  // Mirrors what utilities/_spacing-utilities.scss actually loops to, which
  // itself mirrors the numeric --space-* custom properties
  // tokens/_spacing-tokens.scss generates.
  const numericScaleEnd =
    cfg.spacingSetup.approach === 'coupled' ? cfg.spacingSetup.numericScaleEnd : cfg.spacingSetup.numericScaleMacroEnd

  const typographyConfigDriven = [
    flags.typographyTrim &&
      `- Trim text (font-family + leading-trim + baseline size): ${list(fontRoleKeys, 'trim-text-')}`,
    flags.typographyFamily && `- Font family only: ${list(fontRoleKeys, 'font-family-')}`,
    flags.typographySize && `- Font size only: ${list(fontSizeKeys, 'font-size-')}`,
    flags.typographyLineHeight &&
      `- Line height only: ${list(lineHeightKeys, 'line-height-')}, plus \`.line-height-dynamic\``,
    flags.typographyWeight && `- Font weight only: ${list(fontWeightKeys, 'font-weight-')}`,
  ].filter(Boolean)

  const typographyFixed = [
    flags.typographyStyle && '`.font-style-{normal|italic|oblique}`',
    flags.typographyTextTransform && '`.text-transform-{capitalize|uppercase|lowercase}`',
    flags.typographyTextAlign && '`.text-align-{left|center|right}`',
    flags.typographyNumericFigures && '`.num-{lining|oldstyle|ordinal}-{tabular|proportional}`',
    '`.text-color-inherit`',
  ].filter(Boolean)

  const spacingSections = [
    flags.spacingTshirt &&
      `## Spacing (config-driven t-shirt tiers, from \`spacingSetup\`)

Sizes: ${backticks(spacingKeys)}

Margin/padding properties: ${backticks(spacingProperties)} (e.g. \`.p-md\`, \`.mt-lg\`)`,
    flags.spacingNumeric &&
      `## Spacing (config-driven numeric scale, from \`spacingSetup.numericScaleEnd\`/\`numericScaleMacroEnd\`)

Numeric scale \`1\`–\`${numericScaleEnd}\` for all of the above (e.g. \`.m-12\`).`,
    flags.spacingBase &&
      `## Spacing (fixed)

\`.m-none\`, \`.p-none\`, \`.mx-auto\`, \`.my-auto\`, \`.mr-auto\`, \`.ml-auto\``,
  ].filter(Boolean)

  return `# Utility Classes
<!-- AUTO-GENERATED by \`trimscale-css generate\` from this project's trimscale.config.ts — do not edit by hand. -->

The "config-driven" sections below list the exact classes your current
\`trimscale.config.ts\` produces. The "fixed" sections never change, they're
listed here for a single one-stop reference; see
node_modules/trimscale-css/docs/utility-classes.md for full usage examples.
A section is left out entirely if this project's \`utilities\` config turns
it off, see docs/utility-classes.md#opting-out-of-utility-classes.

## Typography (config-driven, from \`fontRoles\`/\`semanticFontSizes\`/\`fontWeights\`/\`lineHeights\`)

${typographyConfigDriven.length > 0 ? typographyConfigDriven.join('\n') : '_none enabled_'}

## Typography (fixed)

${typographyFixed.join(', ')}

${spacingSections.join('\n\n')}

## Text Box (fixed)

\`.text-box\`, \`.text-box--flow\`, \`.text-box--prose\`, \`.text-box--center-content\`, \`.text-box-{45|50|55|60|65|70|75}\`

## Accessibility (fixed)

\`.sr-only\`, \`.sr-only-focusable\`, \`.focus-none\`, \`.focus-visible\`, \`.skip-link\`, \`.aria-live-polite\`, \`.aria-live-assertive\`
`
}
