/**
 * Written into `<output.dir>` only when `output.reset` is `false`, so the
 * requirement shows up in the consumer's own project instead of needing to
 * be found in this package's README. trimscale-css's spacing and vertical
 * rhythm assume every one of these holds; skipping the package's reset
 * without replacing what it does compiles cleanly and fails silently,
 * describing the symptom (not just the fix) matters here since nothing
 * else will point at the cause.
 */
export const buildResetRequirementsMarkdown = (): string => `# Reset Requirements
<!-- AUTO-GENERATED by \`trimscale-css generate\`. Do not edit by hand. Written because this project's \`output.reset\` is \`false\`. -->

This project has turned off trimscale-css's own \`@layer reset\` block
(\`output.reset: false\`). The typography and spacing system assumes at
least the following, provided by your own reset instead:

- \`margin: 0\` on headings, paragraphs, lists, \`blockquote\`, and \`figure\`
- \`body { margin: 0 }\`
- \`box-sizing: border-box\` throughout
- Nothing that reintroduces \`line-height: normal\` on elements meant to
  inherit \`--line-height-dynamic\`

All of it must live in \`@layer reset\`. Unlayered CSS wins over **every**
layer regardless of specificity, so a reset outside the layer would
override the whole system, not just browser defaults.

## Why this is easy to miss

A popular reset like \`normalize.css\` **keeps** margins on headings and
paragraphs, so following generic "bring your own reset" advice can still
leave the assumptions above unmet. Nothing fails to compile either way,
the system just looks slightly wrong: unexpectedly large gaps between
headings and body text, spacing tokens that look like they aren't being
applied. If that's what you're seeing, check this list first.
`
